### ISSUE TITLE
message signing [question]

### ISSUE THREAD

**Issue by dchagniot** [libp2p/cpp-libp2p#154]
I am using C++ libp2p with Rust libp2p peers in a gossip network (I use the gossip example as starting point).

Peers are connecting without issue.
I may send a message from a rust peer and the other rust and C++ peers get it.

But if the C++ peer sends a message, the rust peers are rejecting it:
the message is not signed and the gossip configuration of the rust peers want a message signed.

Is it possible for C++ libp2p to sign the message before sending it ?

**Comment by turuslan** [comment]
Please check if it works now, with gossip `config.sign_messages = true`

**Comment by dchagniot** [comment]
perfect, thanks
this is working now with the rust gossipsub-chat example
