### ISSUE TITLE
migrate this implementation to the libp2p org?

### ISSUE THREAD

**Issue by raulk** [libp2p/cpp-libp2p#65]
We discussed this elsewhere, but the conversation died down and I want to resurface.

The work done here is brilliant, and a lot more folks could benefit from it – if they knew it existed! Transferring this repo to the libp2p org would help tremendously with discoverability.

Of course, all committers here would preserve their repo rights, and would officially join the libp2p organisation on GitHub -- with a cool new badge to display on their profiles.

Can we make it happen soon? 😇 The proposed repo name is `libp2p/cpp-libp2p`.

**Comment by daviddias** [comment]
Yes please! 🙏🏽

**Comment by raulk** [comment]
ping @kamilsa

**Comment by kamilsa** [comment]
@raulk Sorry, missed the message. We will take that into action ASAP

**Comment by raulk** [comment]
Thanks @kamilsa. We just need you to add the proper licenses on the repo (MIT and ASLv2) before we conduct the transfer.  Have a look at how the licenses in jvm-libp2p are set up for an example! Thank you.

**Comment by kamilsa** [comment]
@raulk noted. Will get back to you when it is done

**Comment by kamilsa** [comment]
@raulk hope now license is good

**Comment by raulk** [comment]
Looks great! Can you make me an admin on this repo so I can perform the migration? @kamilsa

**Comment by kamilsa** [comment]
@raulk 
![image](https://user-images.githubusercontent.com/9370151/84510298-a08ba180-accd-11ea-8192-793dc48d1f7a.png)

**Comment by raulk** [comment]
@kamilsa thanks! I've completed the migration, created a cpp-libp2p group inside the libp2p org, invited all maintainers listed in the repo's readme (@Warchant, @kamilsa, @harrm, @masterjedy, @igor-egorov, @art-gor), and given you all "Maintain" access ;-)

Welcome to the official libp2p org! 🥳 

![](https://media.giphy.com/media/blSTtZehjAZ8I/giphy.gif)
