### ISSUE TITLE
uninitialized local variables - warning as error build issue

### ISSUE THREAD

**Issue by woodsmc** [libp2p/cpp-libp2p#71]
Hi Folks, while building I encountered a number of "warnings treated as errors" during the build, this prevented the build from completing. These were uninitialized local variables in:

- crypto_provider_impl.cpp
- rsa_provider_impl.cpp
- kad_impl.cpp

I've a fix for this I can submit.

**Comment by kamilsa** [comment]
@woodsmc good. Feel free to open a PR
