### ISSUE TITLE
Adding new maintainers

### ISSUE THREAD

**Issue by kamilsa** [libp2p/cpp-libp2p#78]
What should be the process of adding new maintainers? At the moment I need to add @turuslan. In future I might need some more members like some DevOps guys

**Comment by kamilsa** [comment]
@raulk ping

**Comment by raulk** [comment]
Oops @kamilsa, missed this! Adding. Feel free to shoot me an email or Slack message for things like this.

**Comment by raulk** [comment]
Invitation sent!
