### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by meganthomas** [libp2p/cpp-libp2p#82]
Are examples developed of chat applications like the go-libp2p / chat-with-rendezvous? I searched but was not able to found it. Thanks
Megan

**Comment by kamilsa** [comment]
@meganthomas Hi!
Do you mean such example https://github.com/libp2p/go-libp2p-examples/tree/master/chat-with-rendezvous ?
Indeed there is no such example so far, although I agree it is good to have it. We will put this task into our backlog, thanks!

**Comment by kamilsa** [comment]
https://github.com/libp2p/cpp-libp2p/tree/master/example/02-kademlia
